### ISSUE TITLE
yarn generate fails when querying GTFS API

### ISSUE THREAD

**Issue by landonreed** [conveyal/gtfs-tiler#1]
`yarn generate` fails when running with `localhost` api endpoint and single feed ID.

error log:
```
Checking cache for e6c3c80d-055f-4866-bbba-c8a01271c5ba
- not found, querying GTFS API..
SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at /Users/landon/conveyal/gtfs-tiler/node_modules/node-fetch/lib/body.js:48:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
✨  Done in 0.41s.
```

config.js
```
feeds: [
    'e6c3c80d-055f-4866-bbba-c8a01271c5ba'
  ],

  /* The GTFS API endpoint to query. */
  api: {
    gtfs: 'http://localhost:9966/api/manager'
  },
```

**Comment by demory** [comment]
API endpoint was missing `/graphql` at end. Have updated `config-template` to make more clear.
